name: Deploy Node.js Backend to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Upload code to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY}}
          source: "."
          target: "/home/ubuntu/backend-new-code"
          strip_components: 1
          overwrite: true

      - name: Deploy + restart backend
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY}}
          script: |
            sudo rsync -av --delete /home/ubuntu/backend-new-code/ /var/www/backend/

            cd /var/www/backend

            npm ci --omit=dev

            pm2 delete backend 2>/dev/null || true
            pm2 start "node server.js" --name backend

            pm2 save

            echo "Backend is now running on port 5000"
            pm2 status

            rm -rf /home/ubuntu/backend-new-code